### ISSUE TITLE
Write an int64 bohrium array into an int64 numpy array gives segmentation fault

### ISSUE THREAD

**Issue by Ektorus** [bh107/bohrium#3] opened 2015-05-27 10:38 UTC
The following code:
```python
import numpy as np
import bohrium as bh

a = bh.arange(10000, dtype=np.int64)
b = np.empty(10000, dtype=np.int64)
print a.dtype, b.dtype

b[:] = a[:]
print "Done"
```
Gives segementation fault.

**Comment by madsbk** [comment] 2015-06-08 14:18
The data type does not effect this issue thus it is a duplicate of #4.

**Closed by madsbk** 2015-06-08 14:18 UTC
Labels: duplicate
